version: '3'
services:

##############################################################################
# start test clients

  ubuntu-14.04:
    container_name: 'ubuntu-14.04'
    build:
      context: ./ubuntu/
      args:
        UBUNTU_VERSION: 14.04
        RDP_PACKAGE: linuxvnc
    ports:
      - "127.0.0.1:14389:3389"
    restart: unless-stopped
    networks:
      guacnetwork-previous:
      guacnetwork-new:
      guacnetwork-git:

  ubuntu-16.04:
    container_name: 'ubuntu-16.04'
    build:
      context: ./ubuntu/
      args:
        UBUNTU_VERSION: 16.04
        RDP_PACKAGE: vnc4server
    ports:
      - "127.0.0.1:16389:3389"
    restart: unless-stopped
    networks:
      guacnetwork-previous:
      guacnetwork-new:
      guacnetwork-git:

  ubuntu-18.04:
    container_name: 'ubuntu-18.04'
    build:
      context: ./ubuntu/
      args:
        UBUNTU_VERSION: 18.04
        RDP_PACKAGE: xorgrdp
    ports:
      - "127.0.0.1:18389:3389"
    restart: unless-stopped
    networks:
      guacnetwork-previous:
      guacnetwork-new:
      guacnetwork-git:

# end test clients
##############################################################################


##############################################################################
# start guacamole front-ends

  guacamole-previous:
    container_name: 'guacamole-previous'
    image: guacamole/guacamole:${PREVIOUS:-1.0.0}
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd-previous
      POSTGRES_HOSTNAME: postgres-previous
      POSTGRES_DATABASE: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    depends_on:
      - postgres-previous
      - guacd-previous
    networks:
      guacnetwork-previous:
      guacdb:

  guacamole-new:
    container_name: 'guacamole-new'
    image: guacamole/guacamole:${NEW:-1.1.0}
    ports:
      - "127.0.0.1:8081:8080"
    restart: unless-stopped
    environment:
      GUACD_LOG_LEVEL: debug
      GUACD_HOSTNAME: guacd-new
      POSTGRES_HOSTNAME: postgres-new
      POSTGRES_DATABASE: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    depends_on:
      - postgres-new
      - guacd-new
    networks:
      guacnetwork-new:
      guacdb:

  guacamole-git:
    container_name: 'guacamole-git'
    build: ./guacamole-client/
    ports:
      - "127.0.0.1:8082:8080"
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd-git
      POSTGRES_HOSTNAME: postgres-git
      POSTGRES_DATABASE: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    depends_on:
      - postgres-git
      - guacd-git
    networks:
      guacnetwork-git:
      guacdb:

# end guacamole front-ends
##############################################################################

##############################################################################
# start guacamole back-ends

  # specific version of guacd
  guacd-previous:
    container_name: 'guacd-previous'
    image: guacamole/guacd:${PREVIOUS:-1.0.0}
    restart: unless-stopped
    environment:
      GUACD_LOG_LEVEL: debug
    networks:
      guacnetwork-previous:

  # specific version of guacd
  guacd-new:
    container_name: 'guacd-new'
    image: guacamole/guacd:${NEW:-1.0.0}
    restart: unless-stopped
    environment:
      GUACD_LOG_LEVEL: debug
    networks:
      guacnetwork-new:

  # guacd built from latest upstream source
  guacd-git:
    container_name: 'guacd-git'
    build: ./guacamole-server/
    restart: unless-stopped
    environment:
      GUACD_LOG_LEVEL: debug
    networks:
      guacnetwork-git:

# end guacamole back-ends
##############################################################################

##############################################################################
# start guacamole databases

  postgres-previous:
    container_name: 'postgres-previous'
    build:
      context: ./postgres/
      args:
        GUAC_VERSION: ${PREVIOUS:-1.0.0}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    volumes:
      - db_data-previous:/var/lib/postgresql/data
    networks:
      guacdb:

  postgres-new:
    container_name: 'postgres-new'
    build:
      context: ./postgres/
      args:
        GUAC_VERSION: ${NEW:-1.1.0}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    volumes:
      - db_data-new:/var/lib/postgresql/data
    networks:
      guacdb:

  postgres-git:
    container_name: 'postgres-git'
    build:
      context: ./postgres/
      args:
        GUAC_VERSION: ${NEW:-1.1.0}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    volumes:
      - db_data-git:/var/lib/postgresql/data
    networks:
      guacdb:

# end guacamole databases
##############################################################################

##############################################################################
# start volumes and networks

volumes:
  db_data-previous:
    driver: local
  db_data-new:
    driver: local
  db_data-git:
    driver: local

networks:
  guacnetwork-previous:
  guacnetwork-new:
  guacnetwork-git:
  guacdb:

# end of volumes and networks
##############################################################################
